name: Pact Consumer Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run pact tests
        run: npm run pact:test

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: "Pact Release"
          tag_name: pact-latest
          files: ./pact/pacts/*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
